### ISSUE TITLE
multiple domains not working for me

### ISSUE THREAD

**Issue by dragondreams19** [rehmatworks/serverpilot-letsencrypt#10]
hello, i have updated to the latest version and ran the command rwssl -n appname and it showed all domains listed as being able to access the site and completes successfully but when I try to use one of those domains I just secured I get an error saying the cert is only valid for one of the domains on the list and not the others which throws the secure error page message.

**Comment by dragondreams19** [comment]
rwssl -n gemlinks
Obtaining SSL certificate for the app gemlinks.
SSL certificate has been successfully obtained for gemlinks.tk gemme.tk nryou.tk rylgems.tk www.gemlinks.tk www.gemme.tk www.nryou.tk www.rylgems.tk
Writing NGINX vhost file for the app gemlinks
Virtual host file created!
Reloading NGINX server...
SSL should have been installed and activated for the app gemlinks
root@boldcitygems:~#

**Comment by rehmatworks** [comment]
Hi @dragondreams19, I see that SSL is active for all the domains you mentioned. It must be caching issue for you where your browser is still loading the old SSL cert. Please clear browser cache or check in private window. Everything looks good.

**Comment by dragondreams19** [comment]
Thanks for your reply but i figured it out. the server had duplicate conf files from where i used the previous version of rwssl.

**Comment by dragondreams19** [comment]
is it possible to exclude a domain name from getting a duplicate cert?
