### ISSUE TITLE
ignore certain domain names

### ISSUE THREAD

**Issue by dragondreams19** [rehmatworks/serverpilot-letsencrypt#11]
is it possible to ignore certain domain names from getting a duplicate cert and only request a cert for newly added domains on the app?

**Comment by rehmatworks** [comment]
Multiple SSL certificates aren't retrieved. Instead, all domain names are provided as SANs and a single SSL cert is issued for an app. If you still need to exclude some selected domains, I'll introduce that feature in next major version upgrade.

**Comment by dragondreams19** [comment]
okay thanks, i have a url shortner and it allows the user to pick from a list of domains to use as the shortner address and still need to add a few more just didnt wanna request same cert over and over.

**Comment by rehmatworks** [comment]
As a single SSL vhost is created for an app that contains all domains belonging to it, currently it is the best approach to run the install command `rwssl -n appname` each time you add a new domain. I'm closing this issue for now and I'll consider this in next upgrade.
