### ISSUE TITLE
DNS Check Failed

### ISSUE THREAD

**Issue by bekircem** [rehmatworks/serverpilot-letsencrypt#12]
Hi.

I've error when run rwssl -a command. 

```
root@***********r:~# rwssl -a
Finding apps...
4 apps found in total. Proceeding further...
Obtaining SSL certificate for the app gotfrm.
Certbot (Let's Encrypt libraries) not found. Installing libs.
Finished installing required libraries.
Retrying SSL certificate retrieval for the app gotfrm.
DNS check failed. Please ensure that the domain(s) old.******.com www.old.****.com are resolving to your server as well as you have provided the correct root path of your app (including public).
Obtaining SSL certificate for the app gotviki.
DNS check failed. Please ensure that the domain(s) viki.*******.com www.viki.********.com are resolving to your server as well as you have provided the correct root path of your app (including public).
Obtaining SSL certificate for the app zettabayt.
Something went wrong. SSL certificate cannot be installed for server-zettabayt zettabayt.com www.zettabayt.com
Obtaining SSL certificate for the app ******.
Something went wrong. SSL certificate cannot be installed for server-*******
*****.com www.******.com

```
How can i fix that?

**Comment by rehmatworks** [comment]
Ensure that your domains are live and they come up. If they are accessible from the intended server, then please re-run the command `rwssl -a`.

**Comment by bekircem** [comment]
Domains are live. Could this be the problem? There are 3 apps on Serverpilot. All apps are use 1 domain. www.site.com and forum.site.com and viki.site.com

**Comment by rehmatworks** [comment]
That shouldn't be an issue. Please re-run the command and see what does come up.

**Comment by bekircem** [comment]
Ok. It works now. But 301 redirect doesn't work. 

When i run `rwssl -redir all` command:

root@gameofthronestr:~# rwssl -redir all
Finding apps...
3 apps found in total. Proceeding further...
2 SSL apps found for which HTTP to HTTPS redirect is being enabled.
HTTP to HTTPS redirect configuration file has been written successfully.
Reloading NGINX server...
Reloading nginx-sp configuration: nginx-sp.
HTTP to HTTPS redirect has been forced for viki.gameofthronestr.com.
HTTP to HTTPS redirect configuration file has been written successfully.
Reloading NGINX server...
Reloading nginx-sp configuration: nginx-sp.
HTTP to HTTPS redirect has been forced for gameofthronestr.com www.gameofthronestr.com.

But site is down. ERR_TOO_MANY_REDIRECTS

**Comment by rehmatworks** [comment]
Glad to know that you got it working. Regarding the wildcard domain, the script currently isn't capable of obtaining wildcard SSL certs. I'll introduce this feature in next update.

**Comment by bekircem** [comment]
Thank you for answer. Must i install another SSL to my subdomain?

**Comment by rehmatworks** [comment]
As of now, you need to just run `rwssl -a` or install the SSL for each app individually as `rwssl -n appname`. You don't need to enter domain names manually. The script will read your vhost files and will extract all domains automatically that you have added in your ServerPilot control panel.

**Comment by fuad02** [comment]
mine is still error: 
rwssl -n alherbalid
Obtaining SSL certificate for the app alherbalid.
2 valid domains found for the app
DNS check failed. Please ensure that the domain(s) alherbal.id www.alherbal.id are resolving to your server.
I try to find solution above but none of these work, can you help me? thanks

**Comment by rehmatworks** [comment]
Maybe you are using the old version? Can you please install the latest version?

```python
pip3 uninstall rwssl
pip3 install --upgrade --force-reinstall rwssl
```
And try obtaining the SSL again. If there isn't any misconfiguration in DNS or if there isn't any CDN like Cloudflare is masking your origin server, all should work.

**Comment by fuad02** [comment]
here's what I got when I try unstall rwsll
pip3 uninstall rwssl
Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
