### ISSUE TITLE
Multisite Maximum Domain Name

### ISSUE THREAD

**Issue by digitalwordings** [rehmatworks/serverpilot-letsencrypt#13]
What is the maximum domain name for multisite setup?

**Comment by rehmatworks** [comment]
Can you please elaborate a little more? If you are talking about the number of domains than there is a limit of 100 domains per certificate and this limit is imposed by Let's Encrypt.

**Comment by digitalwordings** [comment]
If i have more than 100 domain in my multisite setup, how this actually work?

Then, is this possible to obtain individual ssl for each domain name in multisite setup, because it can be used for multisite website which has more than 100 subsites with unique domain name

**Comment by rehmatworks** [comment]
Yes, that sounds a better idea. I'll consider domain name based vhost files instead using app name in next version. That should solve all issues related to the number of domains for a single app.

**Comment by digitalwordings** [comment]
i think it may be complicated for you, however if you implement this feature it will be great and if you implement this feature give option to disable ssl for particular domains, if you going to implement this let me know, feels excited to test this

**Comment by rehmatworks** [comment]
That shouldn't be complicated. I'll do some testing with this and will add this feature in next version update.
