### ISSUE TITLE
www error (server pilot)

### ISSUE THREAD

**Issue by jesvinjoachim** [rehmatworks/serverpilot-letsencrypt#14]
root@linux:~# rwssl -n matrimonyhrm
Obtaining SSL certificate for the app matrimonyhrm.
DNS check failed. Please ensure that the domain(s) hm.dewsprout.com www.hm.dewsprout.com are resolving to your server.

www.hm.dewsprout.com this gives a problem - because it dosent resolve - can add a ignore subdomain www. to be optional ?

**Comment by rehmatworks** [comment]
Hi @jesvinjoachim, domains are parsed from your `vhost` file. Simply remove the www domain from `domains` tab of your app (in serverpilot control panel) and then retry `rwssl`. Everything should work smoothly.

**Comment by jesvinjoachim** [comment]
since you have developed rwssl -all , i thought it will be easier to just add this www exception too, because its automatically made added just like thath. by the way this all work is awesome , its really good . also i was wondering how much expensive it will be to make a clone of serverpilot , you already have lamppack etc . can we do that ?

**Comment by JamiesonRoberts** [comment]
There is another bug related to this, which is if your www. is listed first in server pilot (and therefor in the vhost) then the script won't run. I was able to fix it by deleting the WWW record in server pilot and reading it, but it should still be able to handle it regardless of the order.

**Comment by rehmatworks** [comment]
@jesvinjoachim adding that exception is easy but the script expects a valid `vhost` file that just contains correct domains. So the best option should be to have only valid domains for your apps in your serverpilot control panel. Regarding a serverpilot clone, I can't say anything about the required budget without doing a complete analysis. If you are serious in a product like this, then we can talk further via email or skype.

**Comment by rehmatworks** [comment]
@JamiesonRoberts Thanks for finding out the bug. Yep that's correct as Let's Encrypt stores certs in a directory for the domain that doesn't contain www but rwssl simply assumes the first domain name as the directory name. I'll fix this issue in next update.

**Comment by jesvinjoachim** [comment]
is this doable with a too much technical strain ? I am student and want to  have a startup .  sure , can you add me in in skype ?  jesvinjoachim . <<please delete the comment as soon as you read it altogether >> after reading and adding me

**Comment by rehmatworks** [comment]
Issues regarding `www` version and invalid domains should be addressed by the new version (1.0.5). Regarding a www domain in sub-domain app, `rwssl` may still through a DNS validation error. Ideally, an app should NOT contain any invalid domains. `rwssl` now only validates a domain name, not it's DNS. So please check `domains` section for your app in ServerPilot control panel and remove any domains that don't belong to your app.

**Comment by jesvinjoachim** [comment]
what you think of developing serverpilot alternative  ?

**Comment by johanguse** [comment]
@jesvinjoachim SP change prices... Free will be over. Check serverpilot Blog.
