### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-FXhuGJ/rwssl/

### ISSUE THREAD

**Issue by amster93** [rehmatworks/serverpilot-letsencrypt#15]
hey, I'm getting this error when I try to install rwssl.
Serverpilot + Ubuntu 18.04

root@test3:~# pip install rwssl
Collecting rwssl
  Using cached https://files.pythonhosted.org/packages/db/81/b339b745e0159c1e5fbc3f6d61517312b2a437b2d276159fcb4e2843144f/rwssl-1.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-FXhuGJ/rwssl/

**Comment by rehmatworks** [comment]
Hi,
Looks like `setuptools` package isn't installed on your system. Please install it:
```bash
sudo apt-get install python-setuptools
```
Hope this fixes the issue.
