### ISSUE TITLE
ServerPilot + Ubuntu 16.04

### ISSUE THREAD

**Issue by mariusherea** [rehmatworks/serverpilot-letsencrypt#16]
I have replaced the old script (which was working just fine) with the new python one but nothing works. 
Requesting a new cert, renewing, refreshing... doesn't work. 
The answer is "SSL should have been installed and activated for the app APPNAME" but it doesn't actually change the cert with the new one.....
I've been trying this on different servers, same result.

**Comment by rehmatworks** [comment]
Maybe you are seeing the cached results from your browser? Please try in a private window or use https://www.sslshopper.com/ssl-checker.html to do a test.

**Comment by mariusherea** [comment]
I found the problem.
I needed to hash -r and hash -d before rwssl -n appname
