### ISSUE TITLE
All apps say they do not resolve

### ISSUE THREAD

**Issue by rea1994** [rehmatworks/serverpilot-letsencrypt#18]
Hello, any of the apps I try to install on say that they don't resolve to my server. How do I fix this? All of the websites are up and running. Not sure what the issue is? Sorry for the question. I'm new to all of this stuff.

**Comment by rehmatworks** [comment]
Can you please check your apps' domains? I suspect that it contains some generic domains added by serverpilot or your websites are behind a CDN like CloudFlare.

**Comment by rea1994** [comment]
No just the www and regular domain with nothing before it. Does your script support Ubuntu 18.04? If not, that might be the issue I’m having. Realized I should say that before making anyone go crazy. :)

**Comment by rehmatworks** [comment]
Thanks for your feedback. I'll do a test on an Ubuntu 18.x server and will fix if any issues are there.

**Comment by rehmatworks** [comment]
Did a test and all went well. It should be a DNS issue for you. Please check and ensure that your all apps contain valid domains that are pointing to your server.
```bash
root@ubuntu-s-1vcpu-1gb-sfo2-01:~# rwssl -n ssltest
Obtaining SSL certificate for the app ssltest.
1 valid domains found for the app
SSL certificate has been successfully obtained for foo.com
Writing NGINX vhost file for the app ssltest
Virtual host file created!
Reloading NGINX server...
SSL should have been installed and activated for the app ssltest
root@ubuntu-s-1vcpu-1gb-sfo2-01:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
root@ubuntu-s-1vcpu-1gb-sfo2-01:~# 
```
