### ISSUE TITLE
This package is intended to be used only on ServerPilot servers. Aborting!

### ISSUE THREAD

**Issue by mmc501** [rehmatworks/serverpilot-letsencrypt#19]
I had this script running ok on my server pilot server and all existing domains ssl enabled.
I have added a new app and now trying to get ssl enabled but I get the error:

This package is intended to be used only on ServerPilot servers. Aborting!

I get that message if i try to run any of the commands.

**Comment by rehmatworks** [comment]
Looks like you are running it without `sudo` privileges. Before executing any commands, the script checks for the existence of ServerPilot's created directories. In your case, seems like you are running it without `sudo` or `root` privileges and thus the script is unable to access the concerned directories.

**Comment by mmc501** [comment]
Exactly the issue - sorry - did everything under root before. Thanks
