### ISSUE TITLE
[Off-Topic] Add support for RunCloud?

### ISSUE THREAD

**Issue by Dibbyo456** [rehmatworks/serverpilot-letsencrypt#2]
[RunCloud.io](https://runcloud.io/) is the best alternative for ServerPilot. I was hoping if you could add support or create similar SSL generator for the free plan. They're almost identical.

**Comment by rehmatworks** [comment]
I haven't used that service yet. Will look into it and will create a script if that makes sense. Thanks for mentioning this.

**Comment by jesvinjoachim** [comment]
i just moved to it...

i think its better than serverpilot in perfomance  and features
