### ISSUE TITLE
It's time for RunCloud?

### ISSUE THREAD

**Issue by Dibbyo456** [rehmatworks/serverpilot-letsencrypt#21]
Incase you may not aware that ServerPilot has [removed their Free plan](https://serverpilot.io/blog/2018/06/08/pricing-changes). Meaning you have to pay if you are gonna use their services. Although old servers are not affected, you just can't add new servers unless you pay!

Here comes RunCloud. They offer [free plan](https://runcloud.io/pricing.html) as well. But it does not gives you the ability to add LE SSL.

So, I definitely think now it's time to fork this for RunCloud. They're are very identical, so you don't have to recreate the script from the scratch. I believe a little tweaking will get the job done.

What do you think..?

**Comment by rehmatworks** [comment]
Thanks for the suggestion. I'll give this some time this weekend and will release a RunCloud version.

**Comment by rehmatworks** [comment]
RunCloud version is ready. I hope you find it useful:
https://github.com/rehmatworks/runcloud-letsencrypt
