### ISSUE TITLE
Can't add new domains to existing app

### ISSUE THREAD

**Issue by ricardoaiello** [rehmatworks/serverpilot-letsencrypt#23]
Hi,

First of all, congratulations and thank you for your work.

I wanted to report a bug when adding new domains to an existing ServerPilot app. When trying to issue the new certificate, it always says

> DNS check failed. Please ensure that the domain(s) example.com www.example.com are resolving to your server.

even though all domains are pointed correctly.

Is there any workaround for this?

Thanks,

Ricardo

**Comment by thgweb** [comment]
Similar problem here, have any solution for this?

**Comment by crownvic** [comment]
Yup. The similar problem. Though a domain in question has a .cool zone. I haven't tried with other zones yet.

**Comment by ricardoaiello** [comment]
> Yup. The similar problem. Though a domain in question has a .cool zone. I haven't tried with other zones yet.

The one that raised my issue has a `.life` zone. As far as I know uncommon zones shouldn't be a problem, but I'm no expert on the subject.

**Comment by ricardoaiello** [comment]
Sorry, closed the issue by mistake when replying.

**Comment by crownvic** [comment]
Which option to choose that will not break the server :)

And I should run it with my own domain, right? Not example.com?

```
How would you like to authenticate with the ACME CA?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: Spin up a temporary webserver (standalone)
2: Place files in webroot directory (webroot)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): c
```

**Comment by rehmatworks** [comment]
@crownvic Can you please proceed by selecting `2` and then by providing the `public` directory'a path of your app? I need to see the final output.

**Comment by crownvic** [comment]
here we go....

<img width="982" alt="image" src="https://user-images.githubusercontent.com/5096949/45597030-832d8480-b9ce-11e8-830e-3bb175eabc6c.png">

**Comment by rehmatworks** [comment]
Looks fine, can you try with `rwssl -n lifeiscool`? What does it say? Still DNS validation error is coming up?

**Comment by crownvic** [comment]
```
root@ubuntu-512mb-nyc3-01:/# rwssl -n lifeiscool
Obtaining SSL certificate for the app lifeiscool.
2 valid domains found for the app
DNS check failed. Please ensure that the domain(s) lifeis.cool www.lifeis.cool are resolving to your server.
root@ubuntu-512mb-nyc3-01:/# 
```

**Comment by rehmatworks** [comment]
Thanks for your feedback. I'll look into the issue.

**Comment by ricardoaiello** [comment]
> Hi,
> Can anyone of you run a dry test to see the output? That'll help me fix the issue if it's related to the script:
> 
> ```shell
> certbot certonly --dry-run -d example.com
> ```
> 
> And then provide the public path of the concerned app. Paste below what you get as output of the command.

Hi Rehmat,

Here are the results of my test. Being this a public forum, I replaced the specific data. I can send it to you privately if you need it.

```
root@droplet:~# certbot certonly --dry-run -d example.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log

How would you like to authenticate with the ACME CA?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: Spin up a temporary webserver (standalone)
2: Place files in webroot directory (webroot)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 2
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for example.com
Input the webroot for example.com: (Enter 'c' to cancel): /srv/users/serverpilot/apps/example/public/
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. example.com (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://example.com/.well-known/acme-challenge/l6C3kNZu7UCjv3LGu95XsNsvEAyTUHCtgpijrVFU2E7 [HERE.GOES.MY.IP]: 404

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: example.com
   Type:   unauthorized
   Detail: Invalid response from
   http://example.com/.well-known/acme-challenge/l6C3kNZu7UCjv3LGu95XsNsvEAyTUHCtgpijrVFU2E7
   [HERE.GOES.MY.IP]: 404

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
root@droplet:~# 
```

Hope this helps.

Thanks,

Ricardo

**Comment by rehmatworks** [comment]
@ricardoaiello Thanks for your test as well. As a quick fix, you should add an exception rewrite condition in your .htaccess file if any rewrite rule has been written in your .htaccess file. This line should go before the rewrite rule:

```bash
RewriteCond %{REQUEST_URI} !\.well-known/acme-challenge
```

If you need a live example, when forcing HTTPS and non-www on a site, we will have to use the exception like this:
```bash
RewriteCond %{HTTP_HOST} ^www\.(.*)
RewriteCond %{REQUEST_URI} !\.well-known/acme-challenge
RewriteRule ^.*$ https://%1/$1 [R=301,L]
```
I'll update the script to handle this without `.htaccess` content modification but for now you can modify your .htaccess file to obtain SSLs.

**Comment by ricardoaiello** [comment]
> @ricardoaiello Thanks for your test as well. As a quick fix, you should add an exception rewrite condition in your .htaccess file if any rewrite rule has been written in your .htaccess file. This line should go before the rewrite rule:
> 
> ```shell
> RewriteCond %{REQUEST_URI} !\.well-known/acme-challenge
> ```
> 
> If you need a live example, when forcing HTTPS and non-www on a site, we will have to use the exception like this:
> 
> ```shell
> RewriteCond %{HTTP_HOST} ^www\.(.*)
> RewriteCond %{REQUEST_URI} !\.well-known/acme-challenge
> RewriteRule ^.*$ https://%1/$1 [R=301,L]
> ```
> 
> I'll update the script to handle this without `.htaccess` content modification but for now you can modify your .htaccess file to obtain SSLs.

Hi Rehmat,

Thanks for your answer.

I'm handling the `http` to `https` redirection using the `-redir` option of your script. So I understand I should make this change in other file rather than the public `.htaccess` of the specific app. Am I correct?

Thanks again,

Ricardo

**Comment by ricardoaiello** [comment]
Hi Rehmat,

I still can't figure out where to add that fix. I'm trying in the `.htaccess` file of the site, but it doesn't seem to work.

Should I be looking somewhere else?

Thanks,

Ricardo

**Comment by matirosero** [comment]
Hi Rehmat,

I'm having the same issue, I ran a dry run and get the following (changing my domain and app name):

`Saving debug log to /var/log/letsencrypt/letsencrypt.log

How would you like to authenticate with the ACME CA?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: Spin up a temporary webserver (standalone)
2: Place files in webroot directory (webroot)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 2
Plugins selected: Authenticator webroot, Installer None
Starting new HTTPS connection (1): acme-staging-v02.api.letsencrypt.org
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for MYDOMAIN
Input the webroot for MYDOMAIN: (Enter 'c' to cancel): /srv/users/serverpilot/apps/APPNAME/public/
Waiting for verification...
Cleaning up challenges
Resetting dropped connection: acme-staging-v02.api.letsencrypt.org

IMPORTANT NOTES:
 - The dry run was successful.
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.`

**Comment by rehmatworks** [comment]
Releasing an upgrade. That should address all issues.
