### ISSUE TITLE
Certificate limit reached

### ISSUE THREAD

**Issue by tridoan** [rehmatworks/serverpilot-letsencrypt#25]
Hi there,
I keep getting this error for a number of my existing/old apps when doing a "-n APP":

Obtaining SSL certificate for the app portal.
2 valid domains found for the app
SSL certificates limit reached for xyz.domain.com www.xyz.domain.com. Please wait before obtaining another SSL.

I've waited a week and still getting it. Do you know how i would get around this?  Thanks

**Comment by onetrev** [comment]
In ServerPilot you need to remove the www. sub-domain. Your app should only be set for `xyz.domain.com`.

**Comment by rehmatworks** [comment]
Sorry for the delayed reply. I hope it's sorted out now.
