### ISSUE TITLE
TLS-SNI-01 validation reaching end-of-life

### ISSUE THREAD

**Issue by ClearMarble** [rehmatworks/serverpilot-letsencrypt#28]
Hi,

First of all thanks for the amazing script, it's been a lifesaver on my grandfathered free plan.

I just got an email regarding an SSL cert I created with this and wondering what the deal might be. It says the Let's Encrypt client used ACME TLS-SNI-01 domain validation to issue my certificate, that this validation method is reaching end of life and that the client needs to use an alternative one or things will break.

Not sure if this is because I might be using a slightly older version of the script, or if this is just not going to work anymore with this new change.

The main content of the email is copied below for reference. Thanks in advance for your time/advice!

> Your Let's Encrypt client used ACME TLS-SNI-01 domain validation to issue
> a certificate in the past 60 days. Below is a list of names and IP
> addresses validated (max of one per account):
> 
>  _MYDOMAIN_.com (162.243.x.xx) on 2019-01-02
> 
> TLS-SNI-01 validation is reaching end-of-life. It will stop working
> temporarily on February 13th, 2019, and permanently on March 13th, 2019.
> Any certificates issued before then will continue to work for 90 days
> after their issuance date.
> 
> You need to update your ACME client to use an alternative validation
> method (HTTP-01, DNS-01 or TLS-ALPN-01) before this date or your
> certificate renewals will break and existing certificates will start to
> expire.

**Comment by rehmatworks** [comment]
Hi @ClearMarble This is talking about the validation that was used to obtain the SSL. Renewal will fail once they will drop this validation. I'm introducing a new utility that you can use to get SSLs using their latest validation methods. I'll post an update here once I release it.
