### ISSUE TITLE
Conflict with previous letsencrypt script 

### ISSUE THREAD

**Issue by Awilson089** [rehmatworks/serverpilot-letsencrypt#29]
Hi

Apologies if this is off-topic but I'm currently using another serverpilot lets encrypt solution (https://github.com/lesaff/serverpilot-letsencrypt) but it has a lot of issues and fewer features. 

I was wondering if you can see any potential conflicts with moving to your script? and if you have any tips for migration. 

Cheers

**Comment by rehmatworks** [comment]
Hi @Awilson089 This might result result in some conflicts. I'm not 100% sure how the other tool is creating SSL vhosts. Duplicate vhosts may be left there. If you can handle the duplicate vhosts issue, i.e. if you can manually remove them if conflicts arise, you are good to use this one.
