### ISSUE TITLE
SSL certificates limit reached 

### ISSUE THREAD

**Issue by TSerra-PT** [rehmatworks/serverpilot-letsencrypt#30]
Hi guys,

I tried to create a new ssl to my project (with this commad: rwssl -n project-public) however the console gives me this error : " SSL certificates limit reached for ... Please wait before obtaining another SSL.".
I waited almost two weeks and the error still remains. Do i need to wait more time? There is other way to jump this error and create a new ssl?

I will appreciate any help ;)

**Comment by rehmatworks** [comment]
Hi @TSerra-PT Sorry for the trouble you had. Current version wasn't using dry run and if the tool was tried multiple times on an app where domains aren't pointed yet, the limit would reach. If you have waited 7 days, this should work. I'm releasing an upgrade and that should address this issue as well.
