### ISSUE TITLE
Update ACME to version 2

### ISSUE THREAD

**Issue by santigraviano** [rehmatworks/serverpilot-letsencrypt#33]
Hey can you update the repo to use Let's Encrypt new ACME v2?

**Comment by rehmatworks** [comment]
Thank you for your input. I will soon release a major upgrade that will address several issues and I'm planning to use ACME V2 API directly without requiring certbot.

**Comment by onetrev** [comment]
I just wondered if the major upgrade you mentioned @rehmatworks would help with the autorenew issues that still seem to be out there? 

I'm not sure mine have ever renewed properly unless I've restarted my Serverpilot services, Apache / Nginx, then I think maybe they do if it's close to the expiry. The cron job (rwsslrenew) is there in my `/etc/cron.d#` folder, I'm running _rwssl_ v1.0.6, but every three months I end up having to refresh them manually. :(  The manual refresh thankfully works perfectly though!

**Comment by rehmatworks** [comment]
Hi @onetrev, yep, that will work perfectly. The upgrade will bring a lot of improvements and that should fix several bugs that users have been reporting. Please consider end of April as an ETA for this upgrade.

**Comment by lincolnpixel** [comment]
hi, you never responded to my issue

**Comment by rehmatworks** [comment]
Hi @lincolnpixel, I replied to you via email and I hope that was hopeful enough. Please wait for the upgrade to address your issues.

**Comment by rehmatworks** [comment]
Is any volunteer there to provide me a server with serverpilot grand-father plan? I want to run some tests and want to be sure that my new upgrade is backward-compatible. Unluckily, I don't have a server with older serverpilot (free) plan. @lincolnpixel I believe you provided me with root access to a server. If anyone can provide a server for testing (for a day), that'd be great. I've almost completed a major upgrade and will be releasing it as soon as I perform thorough testing.

**Comment by onetrev** [comment]
I have a friend that I can ask if she's okay with this. It just has one small site that is still active, but not that important if it goes down for a bit during testing. If no one else has stepped forward I will ping you here @rehmatworks to get your email if I get the approval.

**Comment by rehmatworks** [comment]
@onetrev Thank you so much.

**Comment by onetrev** [comment]
Sent you server details via email. PS, your website seems to be giving a 522 Connection Error.

**Comment by rehmatworks** [comment]
@onetrev Thank you so much! In terms of my website, I haven't put it live yet.

**Comment by rehmatworks** [comment]
@onetrev Thank you so much for your tremendous support. I'll be releasing the major upgrade later today or tomorrow.
