### ISSUE TITLE
Certificate does not install correctly

### ISSUE THREAD

**Issue by Awilson089** [rehmatworks/serverpilot-letsencrypt#36]
Hi, when I generate a new certificate for an app it finds the domains and installs correctly but the SSL never appears when visiting the URL.

The certifate has been generated in `/etc/letsencrypt/live` and also the *-ssl.conf file in `/etc/nginx-sp/vhosts.d`.

Also cant see anything obvious in the .conf file, any ideas?

**Comment by Awilson089** [comment]
I just had the following email from LetsEncrpyt:

> We recently discovered a bug in the Let's Encrypt certificate authority code, 
> described here:
> 
> https://community.letsencrypt.org/t/2020-02-29-caa-rechecking-bug/114591
> 
> Unfortunately, this means we need to revoke the certificates that were affected 
> by this bug, which includes one or more of your certificates. To avoid 
> disruption, you'll need to renew and replace your affected certificate(s) by 
> Wednesday, March 4, 2020. We sincerely apologize for the issue.
> 
> If you're not able to renew your certificate by March 4, the date we are 
> required to revoke these certificates, visitors to your site will see security 
> warnings until you do renew the certificate. Your ACME client documentation 
> should explain how to renew.
> 
> If you are using Certbot, the command to renew is:
> 
> certbot renew --force-renewal
> 
> If you need help, please visit our community support forum: 
> https://community.letsencrypt.org/t/revoking-certain-certificates-on-march-4/114864

I went back onto my server to renew the SSL using `rwssl -n` but it still doesnt seem to be working.

**Comment by rehmatworks** [comment]
@Awilson089 Sorry for replying late. Were you able to fix this issue? If no, please wait for the next upgrade or you can get in touch with me at contact[at]rehmat.works and I'll try to help you directly.

**Comment by rehmatworks** [comment]
Please upgrade to the latest version.

```shell
pip3 install --upgrade --force-reinstall rwssl
```

And read readme here on GitHub or get help on commands by typing `rwssl -h`

**Comment by bfjare** [comment]
I recently had this same issue as well with the newest version of rwssl
