### ISSUE TITLE
DNS check failed

### ISSUE THREAD

**Issue by cbesot** [rehmatworks/serverpilot-letsencrypt#37]
Hi,
migrate from an old script to yours but no cert was installed. I have a DNS check failed on all domains. However, the domains have been ok for years and nothing has changed on the DNS. Ping and DNS propag tests are ok.
Thanks.

**Comment by cbesot** [comment]
That's ok, just a problem with nginx, not your script.

**Comment by nvmng** [comment]
> That's ok, just a problem with nginx, not your script.

Hi, sorry to bother, how did you fix this problem? I'm currently experiencing it.

**Comment by cbesot** [comment]
I'm sorry, I completely forgot already. I've been working too hard lately!
