### ISSUE TITLE
is it possible to add wilid card support , by the way , it is amazing , keep up the good work ,

### ISSUE THREAD

**Issue by jesvinjoachim** [rehmatworks/serverpilot-letsencrypt#4]

**Comment by rehmatworks** [comment]
Thank you for the suggestion. I'll check into this and will update the repo as soon as I make it work.

**Comment by Dibbyo456** [comment]
@rehmatworks is the latest version using wildcard certificates?

**Comment by rehmatworks** [comment]
@Dibbyo456 not yet, I'll add this feature in next update.

**Comment by wootwoot1234** [comment]
@rehmatworks thanks for the great tool.  I would love to use wildcard certificates too!  :)

**Comment by GiancarloJSantos** [comment]
This feature would be awesome!

Thanks for your generosity

**Comment by rehmatworks** [comment]
Sorry for the delayed reply. I'm introducing a new new utility and I'll consider this feature there.
