### ISSUE TITLE
error

### ISSUE THREAD

**Issue by unni-krishnan-95** [rehmatworks/serverpilot-letsencrypt#41]
`Do you really want to obtain an SSL certificate for the app wp20.mydomain.icu? [Y/N] Y`

`Activating SSL for app wp20.mydomain.icu...`

`'NoneType' object has no attribute 'decode'`
`
am getting this error while requesting SSL- cretificate

**Comment by rehmatworks** [comment]
Is your server behind a proxy, like Cloudflare?

**Comment by rehmatworks** [comment]
Please install the latest version as I've mentioned at #44
