### ISSUE TITLE
DNS issue

### ISSUE THREAD

**Issue by bluehatdesign** [rehmatworks/serverpilot-letsencrypt#42]
I'm getting the following error:

"A possible DNS issue found. <domain> may be pointing to a wrong IP (xxx.xxx.xx.xx)"

The IP address listed is the correct IP for the domain. What would cause this?

**Comment by nabeh** [comment]
How did you resolve this?

**Comment by bluehatdesign** [comment]
I didn't resolve it. I upgraded my serverpilot account so I could use their ssl.
