### ISSUE TITLE
CRON job for Cert Renewal not added during install

### ISSUE THREAD

**Issue by sindit** [rehmatworks/serverpilot-letsencrypt#45]
The certs on my server did not renew and expired the other day. Managed to renew them manually with rwssl. 

The automatic renewal apparently did not work. On inspection I notice that no CRON job had been created. No /etc/cron.weekly/rwssl-sslrenewals is present. 

Reinstalled rwssl with:

pip3 install --upgrade --force-reinstall rwssl

However still no rwssl-sslrenewals CRON job got installed to /etc/cron.weekly/

Can/Should I install such a CRON job manually? 

P.S. OS is Ubuntu 18.04 LTS server (DigitalOcean droplet + ServerPilot).

**Comment by rehmatworks** [comment]
Can you please try cloning the repo and install the package?

```bash
git clone https://github.com/rehmatworks/serverpilot-letsencrypt.git
cd serverpilot-letsencrypt
python3 setup.py install
```

If the CRON job is still not created, please try creating the CRON job manually. You can find the example in setup.py file.

**Comment by sindit** [comment]
Thanks! Cloning and installing did create rwssl-sslrenewals in /etc/cron.weekly/
