### ISSUE TITLE
cron entry not created...

### ISSUE THREAD

**Issue by rrrevin** [rehmatworks/serverpilot-letsencrypt#46]
I followed the pip3 install instructions under "Getting Started", but noticed no weekly cron entry was added to /etc/cron.weekly.
The cron file is mention in the uninstall section. (/etc/cron.weekly/rwssl-sslrenewals)

What should it look like?

**Comment by rrrevin** [comment]
I found this : https://github.com/rehmatworks/serverpilot-letsencrypt/issues/45, but it really should be part of the pip install process, yes?

**Comment by onetrev** [comment]
Same issue here, and as such my certs are about to expire as they were not automatically updated. Bummer.

**Comment by rehmatworks** [comment]
#44 should fix the cron issue as well. Please install the latest version of the script as I've mentioned in the last reply there.

**Comment by rehmatworks** [comment]
And to renew the certs right away, please run:

```bash
/usr/local/bin/certbot renew --non-interactive --config-dir /etc/nginx-sp/le-ssls --post-hook "service nginx-sp reload"
```

And for future renewals, please install the latest version:

```bash
pip3 install rwssl==2.0.4
```

**Comment by rehmatworks** [comment]
e963c96 should address these bugs.
