### ISSUE TITLE
script broke my server

### ISSUE THREAD

**Issue by githubcodi** [rehmatworks/serverpilot-letsencrypt#5]
Hi,
This script has broken my entire server, i was following all instructions correctly, still not sure what was the issue?

**Comment by rehmatworks** [comment]
Sorry to hear about the issue. Can you please post the information on serverpilot logs? That'd be helpful.

**Comment by githubcodi** [comment]
I have restored the droplet images to a previous date, i think i won't find those logs any more. Is it possible that once i create the SSL certificates for my apps, i can remove the script? or this will not work?

**Comment by rehmatworks** [comment]
Please check uninstall instructions. BTW I've upgraded the script and now it should be working fine.
