### ISSUE TITLE
Renew with Cloudflare

### ISSUE THREAD

**Issue by ricardojrgpimentel** [rehmatworks/serverpilot-letsencrypt#6]
Hey, amazing script.
So i have used this in my server and i have cloudflare enabled, will letsencrypt be able to renew the cert?

**Comment by jjroelofs** [comment]
just found out the hard way renewal doesn't work with cloudflare. searching for a solution

**Comment by bekircem** [comment]
SSL work with Cloudflare? Or just renewal problem?

**Comment by ricardojrgpimentel** [comment]
It does work with Cloudflare, and it looks like its still working and the renew was successful in my end @jjroelofs
