### ISSUE TITLE
The script can nolonger add new certs

### ISSUE THREAD

**Issue by RavenNull** [rehmatworks/serverpilot-letsencrypt#7]
I know just within the past few days, SP has updated their Apache version. I don't know if that has anything to do with that but now I get this error message: https://i.imgur.com/gcV4ERT.png

Edit: I'm an idiot. I had the wrong IP on the A record. Please close this issue as the issue doesn't lie with the project but the user.

**Comment by makeshyft-tom-g** [comment]
yup that is my problem now too : (

**Comment by RavenNull** [comment]
@makeshyft-tom-g My guess is it had to do with updating something. I just remember I upgraded apache-sp to a new version shortly before I noticed it stopped working. That's the only thing I can think of that would cause issues.

**Comment by RavenNull** [comment]
@rehmatworks Yeah, I had the wrong IP on my A record but didn't notice because I was connecting over IPv6. Uh, I guess make sure your DNS records are correct.

**Comment by makeshyft-tom-g** [comment]
I think it also has to do with server pilot updating their autoSSL product and stuff.  I couldn`t get it to work no matter what.

**Comment by RavenNull** [comment]
@makeshyft-tom-g I don't know what to tell you. I just made sure my server was fully updated and added a new Let's Encrypt cert to double check that I was the problem.

**Comment by makeshyft-tom-g** [comment]
Hey...no it was a simple droplet on DO .....  but maybe it was digital ocean having trouble communicating with the lets encrypt servers.    Its really weird that I had the same problem as someone else, but for a completely different reason.  I ended up switching to CentMin Mod from serverpilot...... thanks for the script it really helped alot at the time I used it.  All the best

**Comment by makeshyft-tom-g** [comment]
Come to think of it ..... I am still running this script on one of my servers...is there any way to trigger the renewal early to see if its going to work?  .... i don't want to wait till the last minute to find out.  I'm really confused about why it was not working for me.  thanks for any guidance in this

**Comment by rehmatworks** [comment]
I've upgraded the script. Even though the old script was working fine with the latest ServerPilot libs, the new upgraded one should be of great help. Please reclone the script and use it.
