### ISSUE TITLE
Can I install multiple domain SSL on same app from serverpilot ?

### ISSUE THREAD

**Issue by rambalwad** [rehmatworks/serverpilot-letsencrypt#9]
I have wp multi-site and need to install each site domain ssl and currently I am not able to do it, can you please help to resolve this ?

Thank you 
Ram

**Comment by rehmatworks** [comment]
Yes, the updated script takes care of everything. Please reinstall the script and you should be good to achieve what you are talking about.

**Comment by rambalwad** [comment]
Thank you @rehmatworks
